import {
  INTEREST_FARMING_OPTIONS,
  INTEREST_WORKSTYLE_OPTIONS,
  FARMER_FARM_TYPE_OPTIONS,
} from "@/constants/profile";
import type {
  Applicant,
  Opportunity,
  OpportunityManager,
  OpportunityOwner,
} from "@/features/opportunities/types";
import { clampToToyohashiBoundary } from "@/utils/geospatial";

type OpportunitySeed = Omit<
  Opportunity,
  "interestTags" | "workstyleTags" | "farmTypes" | "managingFarmers" | "owner" | "chatRoomId"
>;

const FARM_TEAM_MEMBERS: Omit<OpportunityManager, "sharePercentage">[] = [
  {
    id: "farmer-001",
    name: "佐藤 大地",
    role: "リーダー",
    avatarUrl: "https://source.boringavatars.com/beam/120/farmer-001?colors=0f766e,34d399,bbf7d0",
    tagline: "農場全体の段取りと調整を担当",
  },
  {
    id: "farmer-002",
    name: "田中 美沙",
    role: "副リーダー",
    avatarUrl: "https://source.boringavatars.com/beam/120/farmer-002?colors=4338ca,6366f1,c7d2fe",
    tagline: "新人サポートと安全管理を担当",
  },
  {
    id: "farmer-003",
    name: "伊藤 健司",
    role: "農場管理",
    avatarUrl: "https://source.boringavatars.com/beam/120/farmer-003?colors=f97316,fb923c,fcd34d",
    tagline: "肥培管理と機械整備が専門",
  },
  {
    id: "farmer-004",
    name: "山本 菜々",
    role: "品質管理",
    avatarUrl: "https://source.boringavatars.com/beam/120/farmer-004?colors=db2777,f472b6,f9a8d4",
    tagline: "収穫品質と加工工程をリード",
  },
  {
    id: "farmer-005",
    name: "鈴木 亮介",
    role: "物流調整",
    avatarUrl: "https://source.boringavatars.com/beam/120/farmer-005?colors=0ea5e9,38bdf8,bae6fd",
    tagline: "出荷と配送スケジュールを最適化",
  },
];

const buildManagingFarmers = (seedId: string): OpportunityManager[] => {
  const numericSeed = Number.parseInt(seedId.replace(/\D/g, ""), 10) || 0;
  const manager = FARM_TEAM_MEMBERS[numericSeed % FARM_TEAM_MEMBERS.length];

  return [
    {
      ...manager,
      sharePercentage: 100,
    },
  ];
};

const buildOwner = (managers: OpportunityManager[]): OpportunityOwner => {
  const leader = managers.find((manager) => manager.role === "リーダー");
  const owner = leader ?? managers[0];
  return {
    id: owner.id,
    name: owner.name,
    avatarUrl: owner.avatarUrl,
    tagline: owner.tagline,
  };
};

const OPPORTUNITY_SEEDS: OpportunitySeed[] = [
  {
    id: "op-001",
    title: "大葉の朝収穫サポート",
    farmName: "三河香草ファーム",
    description: "豊橋南部のハウスで大葉を朝に摘み取り、選別・束ね作業を担当します。",
    tags: ["大葉", "早朝", "短期"],
    rewardMiles: 900,
    status: "open",
    startDate: "2025-05-12",
    endDate: "2025-05-18",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市老津町南島",
      lat: 34.6765,
      lng: 137.3502,
    },
    capacity: {
      total: 8,
      filled: 3,
    },
  },
  {
    id: "op-002",
    title: "施設トマトの誘引・芽かき",
    farmName: "渥美温室トマト園",
    description: "トマトハウスで誘引や芽かき、潅水のサポートを行います。経験者歓迎。",
    tags: ["トマト", "ハウス", "経験者歓迎"],
    rewardMiles: 1100,
    status: "open",
    startDate: "2025-05-20",
    endDate: "2025-06-05",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市大清水町字大清水",
      lat: 34.6942,
      lng: 137.3151,
    },
    capacity: {
      total: 6,
      filled: 2,
    },
  },
  {
    id: "op-003",
    title: "キャベツの定植と潅水チェック",
    farmName: "高師原ベジタブル",
    description: "露地キャベツの苗を植え付け、潅水ホースの確認やマルチ張りを行います。",
    tags: ["キャベツ", "露地", "未経験歓迎"],
    rewardMiles: 850,
    status: "open",
    startDate: "2025-05-25",
    endDate: "2025-06-02",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市高師本郷町天神",
      lat: 34.7102,
      lng: 137.3648,
    },
    capacity: {
      total: 10,
      filled: 4,
    },
  },
  {
    id: "op-004",
    title: "白ネギの収穫と根切り",
    farmName: "二川野菜カンパニー",
    description: "白ネギを掘り取り、根切り・皮むき・箱詰めまで一連の流れを体験できます。",
    tags: ["白ネギ", "収穫", "日帰り"],
    rewardMiles: 950,
    status: "open",
    startDate: "2025-05-28",
    endDate: "2025-06-08",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市二川町一里山",
      lat: 34.7391,
      lng: 137.4275,
    },
    capacity: {
      total: 9,
      filled: 5,
    },
  },
  {
    id: "op-005",
    title: "葉物野菜の調整とパック詰め",
    farmName: "豊橋グリーンラボ",
    description: "収穫した小松菜とほうれん草をサイズ別に調整し、冷蔵ラインでパック詰めします。",
    tags: ["葉物", "軽作業", "冷房完備"],
    rewardMiles: 780,
    status: "closed",
    startDate: "2025-04-30",
    endDate: "2025-05-15",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市細谷町中道",
      lat: 34.7356,
      lng: 137.3457,
    },
    capacity: {
      total: 12,
      filled: 10,
    },
  },
  {
    id: "op-006",
    title: "夜間ミニトマト収穫チーム",
    farmName: "南栄ハイテク温室",
    description: "夜に稼働するハイテク温室でミニトマトを収穫し、糖度センサーで選別します。",
    tags: ["トマト", "夜間", "高糖度"],
    rewardMiles: 1250,
    status: "open",
    startDate: "2025-06-01",
    endDate: "2025-06-12",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市南栄町東山",
      lat: 34.7008,
      lng: 137.3695,
    },
    capacity: {
      total: 7,
      filled: 1,
    },
  },
  {
    id: "op-007",
    title: "ブロッコリーの出荷準備",
    farmName: "杉山アグリプロジェクト",
    description: "収穫済みブロッコリーの氷詰め・箱詰め・積み込みを行う出荷ライン作業です。",
    tags: ["ブロッコリー", "出荷", "短期"],
    rewardMiles: 820,
    status: "open",
    startDate: "2025-05-18",
    endDate: "2025-05-24",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市杉山町東中",
      lat: 34.659689,
      lng: 137.344336,
    },
    capacity: {
      total: 8,
      filled: 6,
    },
  },
  {
    id: "op-008",
    title: "露地ほうれん草の管理作業",
    farmName: "向山菜園",
    description: "露地農場での除草、防虫ネット張り、収穫前の株張り確認を担当します。",
    tags: ["ほうれん草", "除草", "午前のみ"],
    rewardMiles: 760,
    status: "open",
    startDate: "2025-05-22",
    endDate: "2025-05-31",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市向山区東小路",
      lat: 34.7424,
      lng: 137.413,
    },
    capacity: {
      total: 5,
      filled: 2,
    },
  },
  {
    id: "op-009",
    title: "水耕レタスのシステムチェック",
    farmName: "豊橋ハイドロポニカ",
    description: "水耕レタス工場で培養液の数値チェックや自動収穫ロボの監視を行います。",
    tags: ["レタス", "水耕栽培", "軽作業"],
    rewardMiles: 980,
    status: "closed",
    startDate: "2025-05-01",
    endDate: "2025-05-25",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市明海町工業団地内",
      lat: 34.667717,
      lng: 137.354948,
    },
    capacity: {
      total: 9,
      filled: 7,
    },
  },
  {
    id: "op-010",
    title: "高師原レタスの梱包ライン",
    farmName: "高師原アグリ協同",
    description: "採れたてレタスを冷却しながら袋詰め・ラベル貼りを行うライン作業です。",
    tags: ["レタス", "出荷", "冷房完備"],
    rewardMiles: 780,
    status: "open",
    startDate: "2025-05-27",
    endDate: "2025-06-03",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市高師町北原",
      lat: 34.7067,
      lng: 137.3551,
    },
    capacity: {
      total: 10,
      filled: 5,
    },
  },
  {
    id: "op-011",
    title: "豊川用水の水管理補助",
    farmName: "西部ライスサポート",
    description: "豊川用水を利用した水田で水門開閉や水位管理、ドローン見回りを行います。",
    tags: ["水田", "ドローン", "早朝"],
    rewardMiles: 1300,
    status: "open",
    startDate: "2025-06-10",
    endDate: "2025-06-20",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市中原町東山",
      lat: 34.7825,
      lng: 137.3274,
    },
    capacity: {
      total: 6,
      filled: 1,
    },
  },
  {
    id: "op-012",
    title: "早生品種の田植え支援",
    farmName: "豊橋ふくしまライス",
    description: "乗用田植機への苗補給と畦畔の整備、苗箱洗浄などを担当します。",
    tags: ["稲作", "田植え", "機械補助"],
    rewardMiles: 1050,
    status: "open",
    startDate: "2025-05-18",
    endDate: "2025-05-28",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市植田町池下",
      lat: 34.71374,
      lng: 137.323511,
    },
    capacity: {
      total: 8,
      filled: 4,
    },
  },
  {
    id: "op-013",
    title: "中山間の棚田管理",
    farmName: "石巻棚田保全会",
    description: "北部石巻地区の棚田で畦の草刈り、用水路の泥上げを行います。",
    tags: ["棚田", "草刈り", "地域活動"],
    rewardMiles: 1120,
    status: "open",
    startDate: "2025-06-04",
    endDate: "2025-06-15",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市石巻町西山",
      lat: 34.739876,
      lng: 137.427857,
    },
    capacity: {
      total: 12,
      filled: 6,
    },
  },
  {
    id: "op-014",
    title: "コシヒカリの除草ロボ見守り",
    farmName: "西豊ライスイノベーション",
    description: "自動除草ロボの巡回確認やバッテリー交換、作業ログの記録を行います。",
    tags: ["稲作", "ロボット", "記録"],
    rewardMiles: 1180,
    status: "closed",
    startDate: "2025-05-05",
    endDate: "2025-05-25",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市賀茂町一本木",
      lat: 34.78835,
      lng: 137.370262,
    },
    capacity: {
      total: 5,
      filled: 4,
    },
  },
  {
    id: "op-015",
    title: "飼料米の追肥オペレーター",
    farmName: "豊橋アグロサービス",
    description: "西部水田での肥料散布車の補助と散布後のスカウト記録を実施します。",
    tags: ["稲作", "追肥", "機械補助"],
    rewardMiles: 990,
    status: "open",
    startDate: "2025-06-14",
    endDate: "2025-06-22",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市下五井町沖田",
      lat: 34.759584,
      lng: 137.326405,
    },
    capacity: {
      total: 7,
      filled: 2,
    },
  },
  {
    id: "op-016",
    title: "玄米乾燥施設の監視",
    farmName: "豊橋穀物センター",
    description: "ライスセンターで玄米乾燥機の温度監視、サンプル水分チェックを行います。",
    tags: ["米", "乾燥", "施設"],
    rewardMiles: 1020,
    status: "open",
    startDate: "2025-09-10",
    endDate: "2025-09-24",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市前芝町堤下",
      lat: 34.78406,
      lng: 137.316391,
    },
    capacity: {
      total: 6,
      filled: 0,
    },
  },
  {
    id: "op-017",
    title: "早朝稲刈りチーム",
    farmName: "豊橋稲作ネットワーク",
    description: "コンバイン操作補助と籾輸送、籾すり前の水分チェックを行います。",
    tags: ["稲作", "収穫", "早朝"],
    rewardMiles: 1350,
    status: "open",
    startDate: "2025-09-18",
    endDate: "2025-09-30",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市西七根町池尻",
      lat: 34.677832,
      lng: 137.413918,
    },
    capacity: {
      total: 9,
      filled: 5,
    },
  },
  {
    id: "op-018",
    title: "麦の収穫後耕起サポート",
    farmName: "東三河麦生産組合",
    description: "麦収穫後の農場でトラクター耕起の補助、安全確認、石拾いを行います。",
    tags: ["麦", "耕起", "安全管理"],
    rewardMiles: 920,
    status: "open",
    startDate: "2025-06-26",
    endDate: "2025-07-05",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市神野新田町ロノ割",
      lat: 34.7186,
      lng: 137.3554,
    },
    capacity: {
      total: 8,
      filled: 4,
    },
  },
  {
    id: "op-019",
    title: "水田ドローン撮影アシスタント",
    farmName: "スマートフィールド豊橋",
    description: "生育状況を赤外線ドローンで撮影し、解析用データを整理します。",
    tags: ["スマート農業", "ドローン", "データ解析"],
    rewardMiles: 1400,
    status: "open",
    startDate: "2025-07-02",
    endDate: "2025-07-12",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市東七根町東貝津",
      lat: 34.698152,
      lng: 137.326667,
    },
    capacity: {
      total: 4,
      filled: 1,
    },
  },
  {
    id: "op-020",
    title: "稲刈り仕上げの乾燥調整",
    farmName: "渥美半島ライスマイスター",
    description: "稲刈り後の乾燥調整、色彩選別機設定を行い高品質米の仕上げに携わります。",
    tags: ["稲作", "品質管理", "経験者優遇"],
    rewardMiles: 1500,
    status: "open",
    startDate: "2025-10-01",
    endDate: "2025-10-15",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市小島町西貝津",
      lat: 34.6964,
      lng: 137.3228,
    },
    capacity: {
      total: 5,
      filled: 2,
    },
  },
  {
    id: "op-021",
    title: "富有柿の摘果と袋掛け",
    farmName: "石巻柿の里園",
    description: "北部丘陵地で富有柿の摘果・袋掛け・日焼け防止作業を行います。",
    tags: ["柿", "果樹", "北部"],
    rewardMiles: 980,
    status: "open",
    startDate: "2025-06-08",
    endDate: "2025-06-18",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市石巻本町字市場",
      lat: 34.748045,
      lng: 137.364315,
    },
    capacity: {
      total: 10,
      filled: 6,
    },
  },
  {
    id: "op-022",
    title: "巨峰ハウスの傘紙掛け",
    farmName: "東三河葡萄クラブ",
    description: "巨峰ハウスでの房づくり、摘粒、傘紙掛けを行います。繊細な作業が好きな方向け。",
    tags: ["ぶどう", "ハウス", "繊細作業"],
    rewardMiles: 1120,
    status: "open",
    startDate: "2025-05-30",
    endDate: "2025-06-14",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市東森岡町天神",
      lat: 34.8145,
      lng: 137.4362,
    },
    capacity: {
      total: 8,
      filled: 3,
    },
  },
  {
    id: "op-023",
    title: "梨の仕上げ摘果と草刈り",
    farmName: "下条フルーツガーデン",
    description: "幸水梨園で仕上げ摘果、足元の草刈り、袋掛けの準備を行います。",
    tags: ["梨", "果樹", "草刈り"],
    rewardMiles: 930,
    status: "open",
    startDate: "2025-06-12",
    endDate: "2025-06-22",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市下条東町堀切",
      lat: 34.794368,
      lng: 137.386882,
    },
    capacity: {
      total: 7,
      filled: 3,
    },
  },
  {
    id: "op-024",
    title: "ぶどう収穫と糖度チェック",
    farmName: "石巻丘陵葡萄園",
    description: "ぶどうの収穫・糖度測定・選果を行うピークシーズン支援です。",
    tags: ["ぶどう", "収穫", "選果"],
    rewardMiles: 1250,
    status: "open",
    startDate: "2025-08-05",
    endDate: "2025-08-18",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市石巻町東野",
      lat: 34.790254,
      lng: 137.328334,
    },
    capacity: {
      total: 9,
      filled: 4,
    },
  },
  {
    id: "op-025",
    title: "次郎柿の選別・出荷調整",
    farmName: "豊橋柿選果センター",
    description: "柿のサイズ別選別、渋抜き処理、段ボール詰めを冷蔵施設で行います。",
    tags: ["柿", "選果", "冷房完備"],
    rewardMiles: 880,
    status: "open",
    startDate: "2025-10-12",
    endDate: "2025-10-28",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市東小池町倉番",
      lat: 34.781815,
      lng: 137.337636,
    },
    capacity: {
      total: 12,
      filled: 8,
    },
  },
  {
    id: "op-026",
    title: "いちじくの朝取りと農場管理",
    farmName: "豊橋フィグガーデン",
    description: "朝収穫したいちじくの予冷、農場の潅水チェック、葉の剪定を行います。",
    tags: ["いちじく", "朝収穫", "剪定"],
    rewardMiles: 970,
    status: "open",
    startDate: "2025-07-28",
    endDate: "2025-08-08",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市松井町南新切",
      lat: 34.7857,
      lng: 137.3482,
    },
    capacity: {
      total: 6,
      filled: 2,
    },
  },
  {
    id: "op-027",
    title: "東部りんごの袋掛けサポート",
    farmName: "嵩山フルーツパーク",
    description: "標高の高い東部でりんごの袋掛け、つる回し、風対策を行います。",
    tags: ["りんご", "高地", "季節限定"],
    rewardMiles: 1100,
    status: "open",
    startDate: "2025-06-18",
    endDate: "2025-06-28",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市嵩山町小金",
      lat: 34.842098,
      lng: 137.442754,
    },
    capacity: {
      total: 8,
      filled: 5,
    },
  },
  {
    id: "op-028",
    title: "柚子加工用の収穫支援",
    farmName: "石巻柑橘研究会",
    description: "加工用柚子の収穫、洗浄、搾汁用仕分けを行います。香りに癒やされる作業です。",
    tags: ["柑橘", "収穫", "加工用"],
    rewardMiles: 920,
    status: "open",
    startDate: "2025-11-01",
    endDate: "2025-11-10",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市石巻萩平町新田",
      lat: 34.694112,
      lng: 137.327631,
    },
    capacity: {
      total: 10,
      filled: 6,
    },
  },
  {
    id: "op-029",
    title: "ブルーベリー観光農園スタッフ",
    farmName: "豊橋ブルーベリーの丘",
    description: "摘み取り園での来園者案内、収穫サポート、ジャム加工の補助を行います。",
    tags: ["ブルーベリー", "観光農園", "接客"],
    rewardMiles: 860,
    status: "open",
    startDate: "2025-07-12",
    endDate: "2025-07-26",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市雲谷町長野",
      lat: 34.738396,
      lng: 137.472945,
    },
    capacity: {
      total: 6,
      filled: 5,
    },
  },
  {
    id: "op-030",
    title: "南山梨園の剪定講習と実習",
    farmName: "南山フルーツアカデミー",
    description: "梨の摘心と夏剪定を学べる講習付き実習。講師による技術指導があります。",
    tags: ["梨", "研修", "技能習得"],
    rewardMiles: 1080,
    status: "open",
    startDate: "2025-07-05",
    endDate: "2025-07-15",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市東細谷町北前田",
      lat: 34.7516,
      lng: 137.3642,
    },
    capacity: {
      total: 10,
      filled: 7,
    },
  },
  {
    id: "op-031",
    title: "乳牛搾乳と牛舎清掃",
    farmName: "豊橋ミルクテラス",
    description: "最新のミルキングパーラーで搾乳補助、牛舎の快適性維持のための清掃を実施します。",
    tags: ["酪農", "搾乳", "朝晩"],
    rewardMiles: 1380,
    status: "open",
    startDate: "2025-05-29",
    endDate: "2025-06-30",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市明海町酪農団地",
      lat: 34.665952,
      lng: 137.369462,
    },
    capacity: {
      total: 6,
      filled: 4,
    },
  },
  {
    id: "op-032",
    title: "ブランド豚舎の給餌管理",
    farmName: "豊橋三河ポーク",
    description: "自動給餌システムの補助、子豚の体重測定、環境センサーの記録を行います。",
    tags: ["養豚", "IoT", "衛生管理"],
    rewardMiles: 1320,
    status: "open",
    startDate: "2025-06-03",
    endDate: "2025-06-24",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市伊古部町向山",
      lat: 34.669388,
      lng: 137.382983,
    },
    capacity: {
      total: 5,
      filled: 3,
    },
  },
  {
    id: "op-033",
    title: "うずら卵パッキングライン",
    farmName: "豊橋うずらファーム",
    description: "うずら卵の洗浄・汚れチェック・パッキングを行うクリーンルーム作業です。",
    tags: ["うずら", "軽作業", "衛生管理"],
    rewardMiles: 900,
    status: "open",
    startDate: "2025-05-21",
    endDate: "2025-06-04",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市小島町清田",
      lat: 34.6809,
      lng: 137.3352,
    },
    capacity: {
      total: 9,
      filled: 6,
    },
  },
  {
    id: "op-034",
    title: "採卵鶏舎の環境モニタリング",
    farmName: "豊橋エッグシティ",
    description: "採卵鶏舎の環境センサー値の監視、給餌ラインの点検、鶏舎内巡回を行います。",
    tags: ["養鶏", "センサー", "巡回"],
    rewardMiles: 1180,
    status: "open",
    startDate: "2025-05-26",
    endDate: "2025-06-16",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市天伯町菅沼",
      lat: 34.7082,
      lng: 137.3207,
    },
    capacity: {
      total: 6,
      filled: 2,
    },
  },
  {
    id: "op-035",
    title: "乳製品加工の衛生チェック",
    farmName: "豊橋ミルククラフト",
    description: "自家製ヨーグルト工房での衛生チェック、瓶詰め、ラベル貼りを行います。",
    tags: ["乳製品", "加工", "品質管理"],
    rewardMiles: 940,
    status: "open",
    startDate: "2025-06-07",
    endDate: "2025-06-21",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市大村町山ノ端",
      lat: 34.7548,
      lng: 137.3941,
    },
    capacity: {
      total: 5,
      filled: 4,
    },
  },
  {
    id: "op-036",
    title: "牧草収穫とロールラップ",
    farmName: "豊橋フィードファーム",
    description: "大型ロールベーラーの補助、ラッピング機の操作、搬出を行います。",
    tags: ["牧草", "大型機械", "力仕事"],
    rewardMiles: 1420,
    status: "open",
    startDate: "2025-06-25",
    endDate: "2025-07-06",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市曙町南松原",
      lat: 34.7245,
      lng: 137.3537,
    },
    capacity: {
      total: 6,
      filled: 3,
    },
  },
  {
    id: "op-037",
    title: "赤毛和牛の放牧管理",
    farmName: "三河牧場",
    description: "放牧地での柵点検、牛の健康チェック、給水設備の管理を行います。",
    tags: ["放牧", "家畜管理", "巡回"],
    rewardMiles: 1360,
    status: "open",
    startDate: "2025-05-31",
    endDate: "2025-06-18",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市保美町寺西",
      lat: 34.666018,
      lng: 137.315996,
    },
    capacity: {
      total: 4,
      filled: 2,
    },
  },
  {
    id: "op-038",
    title: "子牛哺乳サポート班",
    farmName: "豊橋ヤングケア",
    description: "生まれたばかりの子牛への哺乳、ベッド整備、健康チェックを行います。",
    tags: ["酪農", "子牛", "夜間交代"],
    rewardMiles: 1480,
    status: "open",
    startDate: "2025-06-09",
    endDate: "2025-06-23",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市天伯町天伯",
      lat: 34.71374,
      lng: 137.323511,
    },
    capacity: {
      total: 5,
      filled: 2,
    },
  },
  {
    id: "op-039",
    title: "畜産バイオガス施設の運転支援",
    farmName: "豊橋アグリエネルギー",
    description: "畜産バイオガスプラントで投入物の計量、発酵槽の温度管理を行います。",
    tags: ["バイオガス", "SDGs", "施設管理"],
    rewardMiles: 1280,
    status: "open",
    startDate: "2025-06-16",
    endDate: "2025-06-30",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市明海町エネルギー拠点",
      lat: 34.674304,
      lng: 137.334717,
    },
    capacity: {
      total: 4,
      filled: 1,
    },
  },
  {
    id: "op-040",
    title: "花苗農家の出荷準備",
    farmName: "豊橋フローラルリンク",
    description: "花苗のラベル付け、トレー積み込み、品質チェックを行います。",
    tags: ["花卉", "出荷", "軽作業"],
    rewardMiles: 780,
    status: "open",
    startDate: "2025-05-23",
    endDate: "2025-05-30",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市東高田町高田",
      lat: 34.7569,
      lng: 137.4248,
    },
    capacity: {
      total: 10,
      filled: 6,
    },
  },
  {
    id: "op-041",
    title: "農業DXインターン（夏期）",
    farmName: "東三河アグリテックラボ",
    description: "豊橋市内のスマート農業現場を巡り、データ収集とレポーティングを行います。",
    tags: ["インターン", "DX", "レポート"],
    rewardMiles: 1500,
    status: "open",
    startDate: "2025-08-01",
    endDate: "2025-08-31",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市駅前大通一丁目55",
      lat: 34.7698,
      lng: 137.3831,
    },
    capacity: {
      total: 6,
      filled: 4,
    },
  },
  {
    id: "op-042",
    title: "農業スタートアップ伴走",
    farmName: "豊橋アグリアクセラレータ",
    description: "農業スタートアップの実証農場で観測、参加者へのヒアリングを行います。",
    tags: ["スタートアップ", "フィールド調査", "ヒアリング"],
    rewardMiles: 1380,
    status: "open",
    startDate: "2025-05-19",
    endDate: "2025-06-09",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市西幸町浜池",
      lat: 34.7561,
      lng: 137.3667,
    },
    capacity: {
      total: 5,
      filled: 2,
    },
  },
  {
    id: "op-043",
    title: "農業見学＆体験ツアーサポート",
    farmName: "豊橋アグリツーリズム協議会",
    description: "見学ツアーでの案内、体験補助、アンケート回収を行います。接客が好きな方向け。",
    tags: ["体験", "接客", "観光"],
    rewardMiles: 800,
    status: "open",
    startDate: "2025-05-31",
    endDate: "2025-06-07",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市瓦町通三丁目",
      lat: 34.7648,
      lng: 137.3854,
    },
    capacity: {
      total: 12,
      filled: 9,
    },
  },
  {
    id: "op-044",
    title: "気候変動モニタリング実証",
    farmName: "豊橋アグリリサーチ",
    description: "農場センサーと気象データの収集、データ可視化のサポートを行います。",
    tags: ["研究", "データ分析", "センサー"],
    rewardMiles: 1400,
    status: "open",
    startDate: "2025-05-27",
    endDate: "2025-06-30",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市南牛川一丁目",
      lat: 34.7607,
      lng: 137.4092,
    },
    capacity: {
      total: 4,
      filled: 1,
    },
  },
  {
    id: "op-045",
    title: "農業機械メンテ研修",
    farmName: "豊橋アグリメンテサービス",
    description: "農機具工場での定期点検、消耗品交換、整備記録の入力を学べます。",
    tags: ["整備", "研修", "機械"],
    rewardMiles: 990,
    status: "open",
    startDate: "2025-06-11",
    endDate: "2025-06-25",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市明海町整備工場街",
      lat: 34.674801,
      lng: 137.324381,
    },
    capacity: {
      total: 8,
      filled: 6,
    },
  },
  {
    id: "op-046",
    title: "地域学校向け食農授業補助",
    farmName: "豊橋フードリテラシー協会",
    description: "市内小学校で食農授業の準備、教材配布、児童サポートを行います。",
    tags: ["食育", "教育", "出張"],
    rewardMiles: 750,
    status: "open",
    startDate: "2025-06-17",
    endDate: "2025-06-24",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市松葉町一丁目",
      lat: 34.7681,
      lng: 137.3867,
    },
    capacity: {
      total: 10,
      filled: 7,
    },
  },
  {
    id: "op-047",
    title: "六次産業化商品開発モック",
    farmName: "豊橋アグリラボ",
    description: "加工品のレシピ試作、パッケージ検討、試食会の運営を行います。",
    tags: ["六次産業化", "商品開発", "試作"],
    rewardMiles: 980,
    status: "open",
    startDate: "2025-06-05",
    endDate: "2025-06-19",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市神明町イノベ拠点",
      lat: 34.7705,
      lng: 137.3812,
    },
    capacity: {
      total: 6,
      filled: 2,
    },
  },
  {
    id: "op-048",
    title: "農業ボランティアコーディネータ",
    farmName: "豊橋市農政課（モック）",
    description: "市内農家とボランティアのマッチング、日程調整、記録作成を行います。",
    tags: ["コーディネート", "事務", "地域連携"],
    rewardMiles: 860,
    status: "open",
    startDate: "2025-05-20",
    endDate: "2025-06-20",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市今橋町市役所前",
      lat: 34.769,
      lng: 137.3836,
    },
    capacity: {
      total: 4,
      filled: 3,
    },
  },
  {
    id: "op-049",
    title: "スマート温室の夜間監視",
    farmName: "豊橋スマートアグリ",
    description: "AI温室の夜間監視、センサー異常時の連絡、環境データの記録を担当します。",
    tags: ["スマート農業", "夜間", "監視"],
    rewardMiles: 1450,
    status: "open",
    startDate: "2025-06-08",
    endDate: "2025-06-22",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市明海町スマート団地",
      lat: 34.673161,
      lng: 137.312871,
    },
    capacity: {
      total: 5,
      filled: 1,
    },
  },
  {
    id: "op-050",
    title: "地域農業フェスタ運営補助",
    farmName: "豊橋アグリフェスタ実行委員会",
    description: "秋に開催される農業フェスタの準備、ブース設営、来場者対応を行います。",
    tags: ["イベント", "秋", "運営"],
    rewardMiles: 820,
    status: "open",
    startDate: "2025-10-20",
    endDate: "2025-11-02",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市向山大池町",
      lat: 34.7629,
      lng: 137.4023,
    },
    capacity: {
      total: 18,
      filled: 11,
    },
  },
  {
    id: "op-051",
    title: "週末1Day田植え体験サポート",
    farmName: "豊橋里山ライスプロジェクト",
    description: "土曜日限定で田植機の補助と手植え体験、集合後の交流ランチを行います。",
    tags: ["稲作", "1Day", "週末限定"],
    rewardMiles: 820,
    status: "open",
    startDate: "2025-05-17",
    endDate: "2025-05-17",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市嵩山町里山",
      lat: 34.838727,
      lng: 137.427863,
    },
    capacity: {
      total: 14,
      filled: 6,
    },
  },
  {
    id: "op-052",
    title: "日曜日限定モーニング牧場ケア",
    farmName: "豊橋モーニングデイリー",
    description: "日曜朝の2時間で乳牛の給餌と搾乳サポート、子牛の健康チェックを行います。",
    tags: ["酪農", "1Day", "日曜限定"],
    rewardMiles: 960,
    status: "open",
    startDate: "2025-05-18",
    endDate: "2025-05-18",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市東細谷町牧場前",
      lat: 34.7498,
      lng: 137.3711,
    },
    capacity: {
      total: 8,
      filled: 3,
    },
  },
  {
    id: "op-053",
    title: "1Dayナイトマーケット販売サポート",
    farmName: "豊橋駅前アグリマルシェ",
    description: "週末夜市での販売準備・接客・片付けを行う1日完結の募集です。",
    tags: ["イベント", "1Day", "週末限定"],
    rewardMiles: 780,
    status: "open",
    startDate: "2025-05-24",
    endDate: "2025-05-24",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市駅前大通二丁目ナイトマーケット会場",
      lat: 34.7701,
      lng: 137.3884,
    },
    capacity: {
      total: 16,
      filled: 10,
    },
  },
  {
    id: "op-054",
    title: "伊古部浜の塩害対策ほ場整備",
    farmName: "伊古部浜ラインファーム",
    description: "沿岸部の水田で潮風による塩害を抑えるための客土と暗渠の補修を行います。トラクター作業の補助と水抜き溝の整備を担当してください。",
    tags: ["水田", "沿岸", "整備"],
    rewardMiles: 1150,
    status: "open",
    startDate: "2025-07-02",
    endDate: "2025-07-08",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市伊古部町砂下",
      lat: 34.669388,
      lng: 137.382983,
    },
    capacity: {
      total: 8,
      filled: 2,
    },
  },
  {
    id: "op-055",
    title: "高塚干潟の潅水ライン点検",
    farmName: "伊古部浜ラインファーム",
    description: "潮位に合わせて可動する潅水配管のリーク確認とポンプ吸水口の清掃を行います。終盤にはセンサー値の記録と共有もお願いします。",
    tags: ["水田", "潅水", "設備"],
    rewardMiles: 1100,
    status: "open",
    startDate: "2025-07-09",
    endDate: "2025-07-15",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市高塚町浜道",
      lat: 34.673574,
      lng: 137.400544,
    },
    capacity: {
      total: 6,
      filled: 1,
    },
  },
  {
    id: "op-056",
    title: "寺沢区画の直播補助クルー",
    farmName: "伊古部浜ラインファーム",
    description: "直播田での播種機追従、種子補給、浅水管理を行います。機械オペレータ補助の経験がある方を歓迎します。",
    tags: ["稲作", "直播", "機械"],
    rewardMiles: 1180,
    status: "open",
    startDate: "2025-07-16",
    endDate: "2025-07-23",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市寺沢町下り松",
      lat: 34.676141,
      lng: 137.430264,
    },
    capacity: {
      total: 5,
      filled: 0,
    },
  },
  {
    id: "op-057",
    title: "西七根潮風ブロックネット設置",
    farmName: "伊古部浜ラインファーム",
    description: "西七根地区の露地畑で、夏季の潮風対策用ネットの設営と支柱補強を行います。軽トラでの資材運搬もお願いします。",
    tags: ["沿岸", "資材", "短期"],
    rewardMiles: 980,
    status: "open",
    startDate: "2025-07-18",
    endDate: "2025-07-20",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市西七根町午新田",
      lat: 34.677832,
      lng: 137.413918,
    },
    capacity: {
      total: 7,
      filled: 3,
    },
  },
  {
    id: "op-058",
    title: "小島海岸レタス育苗サポート",
    farmName: "伊古部浜ラインファーム",
    description: "潮風が強い小島地区で秋作レタスの育苗管理を行います。遮光シートの開閉と潅水ログの記録、苗の健全チェックが主な作業です。",
    tags: ["葉物", "育苗", "沿岸"],
    rewardMiles: 960,
    status: "open",
    startDate: "2025-07-24",
    endDate: "2025-07-31",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市小島町大根山",
      lat: 34.678413,
      lng: 137.44844,
    },
    capacity: {
      total: 6,
      filled: 1,
    },
  },
  {
    id: "op-059",
    title: "小松原圃場の中干しDXモニター",
    farmName: "東七根サンライズ農園",
    description: "水田センサーのデータを見ながらドローンでの水位確認と中干し開始後の畦シール点検を行います。記録はアプリで入力します。",
    tags: ["稲作", "センサー", "ドローン"],
    rewardMiles: 1240,
    status: "open",
    startDate: "2025-07-05",
    endDate: "2025-07-12",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市小松原町西畑",
      lat: 34.678614,
      lng: 137.437274,
    },
    capacity: {
      total: 5,
      filled: 1,
    },
  },
  {
    id: "op-060",
    title: "東七根エリアのスマート潅水調整",
    farmName: "東七根サンライズ農園",
    description: "潅水バルブの切り替えと電磁弁の清掃、EC センサーのキャリブレーションを行います。夜間の水圧確認も含まれます。",
    tags: ["潅水", "センサー", "設備"],
    rewardMiles: 1190,
    status: "open",
    startDate: "2025-07-13",
    endDate: "2025-07-19",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市東七根町浜田",
      lat: 34.68453,
      lng: 137.421312,
    },
    capacity: {
      total: 6,
      filled: 2,
    },
  },
  {
    id: "op-061",
    title: "野依開拓の湿田暗渠メンテ",
    farmName: "東七根サンライズ農園",
    description: "野依開拓地域で暗渠パイプの詰まり解消と集水桝の泥上げを行います。作業後は排水記録をアプリに入力します。",
    tags: ["水田", "排水", "整備"],
    rewardMiles: 1120,
    status: "open",
    startDate: "2025-07-20",
    endDate: "2025-07-27",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市野依町開拓二組",
      lat: 34.684647,
      lng: 137.38762,
    },
    capacity: {
      total: 8,
      filled: 3,
    },
  },
  {
    id: "op-062",
    title: "上細谷棚田の畦塗り＆草刈り",
    farmName: "東七根サンライズ農園",
    description: "細谷地区の棚田で畦塗り、畦畔草刈り、止水板の設置を行います。斜面作業に慣れている方を歓迎します。",
    tags: ["棚田", "草刈り", "畦管理"],
    rewardMiles: 1220,
    status: "open",
    startDate: "2025-07-28",
    endDate: "2025-08-03",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市上細谷町向田",
      lat: 34.684666,
      lng: 137.46366,
    },
    capacity: {
      total: 9,
      filled: 2,
    },
  },
  {
    id: "op-063",
    title: "野依地区の夜間見回りパトロール",
    farmName: "東七根サンライズ農園",
    description: "夜間の水田を巡回し、獣害柵の損傷チェックと水位異常の早期発見を行います。タブレットで報告書を作成します。",
    tags: ["夜間", "パトロール", "獣害対策"],
    rewardMiles: 1280,
    status: "open",
    startDate: "2025-08-01",
    endDate: "2025-08-10",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市野依町開拓三組",
      lat: 34.686618,
      lng: 137.392213,
    },
    capacity: {
      total: 4,
      filled: 0,
    },
  },
  {
    id: "op-064",
    title: "下細谷干拓の追肥撒布サポート",
    farmName: "細谷シーサイドライス",
    description: "下細谷の大区画水田で、GPS 施肥機への資材補給と散布跡の確認を行います。ドローン撮影の補助もお願いします。",
    tags: ["稲作", "追肥", "ドローン"],
    rewardMiles: 1300,
    status: "open",
    startDate: "2025-07-06",
    endDate: "2025-07-13",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市下細谷町川向",
      lat: 34.688203,
      lng: 137.479932,
    },
    capacity: {
      total: 6,
      filled: 1,
    },
  },
  {
    id: "op-065",
    title: "野依開拓六組の水口オペレーター",
    farmName: "細谷シーサイドライス",
    description: "用水路のゲート調整と水口の掃除、通水記録の作成を担当します。スマート水位計の読み取りも行います。",
    tags: ["水田", "用水", "記録"],
    rewardMiles: 1080,
    status: "open",
    startDate: "2025-07-14",
    endDate: "2025-07-21",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市野依町開拓六組",
      lat: 34.690025,
      lng: 137.393428,
    },
    capacity: {
      total: 5,
      filled: 2,
    },
  },
  {
    id: "op-066",
    title: "野依開拓八組の収量マッピング",
    farmName: "細谷シーサイドライス",
    description: "コンバインの収量計データを回収し、圃場ごとのばらつきを可視化します。ドローンの NDVI 撮影補助も含まれます。",
    tags: ["データ解析", "収穫", "ドローン"],
    rewardMiles: 1350,
    status: "open",
    startDate: "2025-08-18",
    endDate: "2025-08-28",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市野依町開拓八組",
      lat: 34.690693,
      lng: 137.401809,
    },
    capacity: {
      total: 4,
      filled: 0,
    },
  },
  {
    id: "op-067",
    title: "ヒルモ干拓の転作枝豆管理",
    farmName: "細谷シーサイドライス",
    description: "ヒルモ地区で枝豆の除草、灌水、収穫前の糖度測定を行います。直売所向けの選別作業もお願いします。",
    tags: ["豆類", "転作", "直売"],
    rewardMiles: 1020,
    status: "open",
    startDate: "2025-08-05",
    endDate: "2025-08-15",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市ヒルモ町若宮",
      lat: 34.691823,
      lng: 137.441164,
    },
    capacity: {
      total: 7,
      filled: 2,
    },
  },
  {
    id: "op-068",
    title: "睦美ビオトープの水質チェック",
    farmName: "細谷シーサイドライス",
    description: "睦美地区のビオトープで水質測定と畦の補修、生き物観察会の案内補助を行います。子ども向けプログラムも予定しています。",
    tags: ["環境", "教育", "生物多様性"],
    rewardMiles: 950,
    status: "open",
    startDate: "2025-07-27",
    endDate: "2025-08-03",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市睦美町片浜",
      lat: 34.692396,
      lng: 137.42957,
    },
    capacity: {
      total: 10,
      filled: 4,
    },
  },
  {
    id: "op-069",
    title: "野依開拓一組の土地改良調査",
    farmName: "野依開拓グリーン協同",
    description: "野依開拓一組で排水路と畦畔の測量、改良計画のヒアリング補助を行います。GIS アプリでの記録ができる方を歓迎。",
    tags: ["調査", "土地改良", "GIS"],
    rewardMiles: 1250,
    status: "open",
    startDate: "2025-07-11",
    endDate: "2025-07-18",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市野依町開拓一組",
      lat: 34.693844,
      lng: 137.384196,
    },
    capacity: {
      total: 6,
      filled: 1,
    },
  },
  {
    id: "op-070",
    title: "野依四組の代かきサポート",
    farmName: "野依開拓グリーン協同",
    description: "小型無人トラクターの代かき運転補助と水位管理、レーザーレベラーの設置を行います。操作研修付きです。",
    tags: ["稲作", "自動運転", "研修"],
    rewardMiles: 1380,
    status: "open",
    startDate: "2025-07-19",
    endDate: "2025-07-26",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市野依町開拓四組",
      lat: 34.694363,
      lng: 137.388104,
    },
    capacity: {
      total: 5,
      filled: 1,
    },
  },
  {
    id: "op-071",
    title: "野依七組の圃場モニタリング",
    farmName: "野依開拓グリーン協同",
    description: "可変施肥を行っている区画で、葉色センサーと土壌ECの測定、試料採取を行います。取得データはクラウドに同期します。",
    tags: ["センサー", "データ", "圃場観察"],
    rewardMiles: 1320,
    status: "open",
    startDate: "2025-07-27",
    endDate: "2025-08-04",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市野依町開拓七組",
      lat: 34.695516,
      lng: 137.397086,
    },
    capacity: {
      total: 4,
      filled: 1,
    },
  },
  {
    id: "op-072",
    title: "野依五組の直播再播チーム",
    farmName: "野依開拓グリーン協同",
    description: "局所的な欠株を補うための局所播種と苗補植、潅水の微調整を行います。タブレットで記録しながら作業します。",
    tags: ["稲作", "補植", "潅水"],
    rewardMiles: 1090,
    status: "open",
    startDate: "2025-08-06",
    endDate: "2025-08-12",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市野依町開拓五組",
      lat: 34.696248,
      lng: 137.392108,
    },
    capacity: {
      total: 6,
      filled: 2,
    },
  },
  {
    id: "op-073",
    title: "野依九組の排水路クリーン作戦",
    farmName: "野依開拓グリーン協同",
    description: "大雨時に負荷がかかる排水路の草刈りと堆積土砂の掻き出しを行います。作業後は水門の開閉テストも実施します。",
    tags: ["排水", "草刈り", "地域活動"],
    rewardMiles: 980,
    status: "open",
    startDate: "2025-08-17",
    endDate: "2025-08-25",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市野依町開拓九組",
      lat: 34.696475,
      lng: 137.402793,
    },
    capacity: {
      total: 12,
      filled: 5,
    },
  },
  {
    id: "op-074",
    title: "野依十組の秋落水準備",
    farmName: "二川スマートアグリ連合",
    description: "収穫に向けた落水スケジュールの調整と水田の水口整理、ドローンでの減水チェックを行います。",
    tags: ["稲作", "落水", "ドローン"],
    rewardMiles: 1200,
    status: "open",
    startDate: "2025-08-05",
    endDate: "2025-08-12",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市野依町開拓十組",
      lat: 34.700282,
      lng: 137.401212,
    },
    capacity: {
      total: 5,
      filled: 1,
    },
  },
  {
    id: "op-075",
    title: "西山地区の麦後ダイズ管理",
    farmName: "二川スマートアグリ連合",
    description: "西山圃場でのダイズ中耕と中耕時の水分測定、リモート気象ステーションの点検を行います。",
    tags: ["大豆", "転作", "中耕"],
    rewardMiles: 990,
    status: "open",
    startDate: "2025-07-30",
    endDate: "2025-08-08",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市西山町二川台",
      lat: 34.700501,
      lng: 137.453454,
    },
    capacity: {
      total: 8,
      filled: 2,
    },
  },
  {
    id: "op-076",
    title: "野依東南の畦畔保全ワーク",
    farmName: "二川スマートアグリ連合",
    description: "東南ブロックで畦畔の法面整備と自動給水タンクの据え付けを行います。緑肥の播種作業も含まれます。",
    tags: ["畦管理", "緑肥", "設備"],
    rewardMiles: 1040,
    status: "open",
    startDate: "2025-08-14",
    endDate: "2025-08-21",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市野依町東南",
      lat: 34.701113,
      lng: 137.393239,
    },
    capacity: {
      total: 9,
      filled: 3,
    },
  },
  {
    id: "op-077",
    title: "野依西南の畔灯り点検",
    farmName: "二川スマートアグリ連合",
    description: "夜間の獣害抑止に使うソーラー畔灯の点検と交換、作動ログの確認を行います。簡単な電気作業が含まれます。",
    tags: ["夜間", "獣害対策", "設備"],
    rewardMiles: 980,
    status: "open",
    startDate: "2025-08-22",
    endDate: "2025-08-29",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市野依町西南",
      lat: 34.701152,
      lng: 137.384244,
    },
    capacity: {
      total: 7,
      filled: 2,
    },
  },
  {
    id: "op-078",
    title: "繩手干拓のポンプ場監視隊",
    farmName: "二川スマートアグリ連合",
    description: "繩手地区の用排水ポンプ場で運転監視、フィルター清掃、遠隔監視システムのログ確認を担当します。",
    tags: ["設備", "排水", "監視"],
    rewardMiles: 1270,
    status: "open",
    startDate: "2025-08-25",
    endDate: "2025-09-03",
    location: {
      prefecture: "愛知県",
      city: "豊橋市",
      address: "豊橋市繩手町南川",
      lat: 34.701579,
      lng: 137.44601,
    },
    capacity: {
      total: 6,
      filled: 1,
    },
  },
];

const INTEREST_VALUES = new Set(INTEREST_FARMING_OPTIONS.map((option) => option.value));
const WORKSTYLE_VALUES = new Set(INTEREST_WORKSTYLE_OPTIONS.map((option) => option.value));
const FARM_TYPE_VALUES = new Set(FARMER_FARM_TYPE_OPTIONS.map((option) => option.value));

type KeywordRule = {
  value: string;
  patterns?: RegExp[];
  predicate?: (seed: OpportunitySeed, text: string) => boolean;
};

const toPatterns = (keywords: string[]) =>
  keywords.map((keyword) => new RegExp(keyword, "i"));

const INTEREST_RULES: KeywordRule[] = [
  { value: "orchard", patterns: toPatterns(["柿", "梨", "ぶどう", "果樹", "巨峰", "ブルーベリー", "りんご", "柚子", "いちじく", "桃", "柑橘"]) },
  { value: "livestock", patterns: toPatterns(["牛", "豚", "鶏", "酪農", "畜産", "乳", "放牧", "うずら", "牧草"]) },
  { value: "technology", patterns: toPatterns(["スマート", "IoT", "センサー", "ドローン", "ロボ", "DX", "AI", "データ", "夜間監視"]) },
  { value: "value_added", patterns: toPatterns(["加工", "商品", "6次", "乾燥", "選別", "ラベル", "パック", "ヨーグルト", "乳製品", "バイオガス", "クラフト"]) },
  { value: "community", patterns: toPatterns(["地域", "コミュニティ", "協議会", "ボランティア", "学校", "教育", "ツアー", "フェスタ", "連携"]) },
  { value: "agritourism", patterns: toPatterns(["観光", "体験", "ツアー", "見学", "フェスタ"]) },
  { value: "conservation", patterns: toPatterns(["保全", "棚田", "環境", "モニタリング"]) },
  { value: "organic", patterns: toPatterns(["有機", "サステナ", "環境保全", "自然循環"]) },
  { value: "heirloom", patterns: toPatterns(["在来", "伝統", "次郎柿"]) },
  { value: "seasonal", patterns: toPatterns(["収穫", "季節", "春", "夏", "秋", "冬", "稲刈", "田植", "麦", "旬"]) },
];

const WORKSTYLE_RULES: KeywordRule[] = [
  {
    value: "short_term",
    predicate: (seed, text) => {
      const duration = getDurationDays(seed);
      return (
        (duration > 0 && duration <= 14) ||
        /短期|日帰り|イベント/.test(text)
      );
    },
  },
  { value: "side_job", patterns: toPatterns(["副業"]) },
  { value: "internship", patterns: toPatterns(["インターン", "研修", "講習", "アカデミー"]) },
  {
    value: "migration",
    predicate: (seed, text) => {
      const duration = getDurationDays(seed);
      return duration >= 30 || /長期|移住/.test(text);
    },
  },
  { value: "hybrid", patterns: toPatterns(["ハイブリッド", "リモート"]) },
  { value: "with_family", patterns: toPatterns(["家族", "友人"]) },
  { value: "education", patterns: toPatterns(["教育", "授業", "ワークショップ", "学校"]) },
  { value: "career_change", patterns: toPatterns(["キャリア", "就農", "転職"]) },
  { value: "weekend_only", patterns: toPatterns(["週末", "土日"]) },
  {
    value: "time_specific",
    predicate: (seed, text) =>
      /夜間|夜|早朝|朝/.test(text) ||
      seed.tags.some((tag) => /夜|朝/.test(tag)),
  },
];

const FARM_TYPE_RULES: KeywordRule[] = [
  { value: "greenhouse", patterns: toPatterns(["ハウス", "温室", "施設園芸", "水耕", "温室", "スマート温室"]) },
  { value: "open_field", patterns: toPatterns(["露地", "畑", "農場", "キャベツ", "ブロッコリー", "ほうれん草", "麦", "草刈", "畦", "耕起"]) },
  { value: "orchard", patterns: toPatterns(["柿", "梨", "ぶどう", "果樹", "ブルーベリー", "りんご", "柚子", "いちじく", "柑橘", "桃"]) },
  { value: "tea", patterns: toPatterns(["茶畑", "茶摘", "茶"]) },
  { value: "rice", patterns: toPatterns(["稲", "米", "田植", "籾", "水田", "コシヒカリ", "玄米"]) },
  { value: "flowers", patterns: toPatterns(["花苗", "花卉", "フローラル"]) },
  { value: "livestock", patterns: toPatterns(["牛", "豚", "鶏", "畜産", "酪農", "乳", "放牧", "うずら", "牧草"]) },
  { value: "value_added", patterns: toPatterns(["加工", "商品", "6次", "バイオガス", "乳製品", "レシピ", "パッケージ", "ラベル", "乾燥", "選別", "出荷", "エネルギー", "クラフト"]) },
];

function getDurationDays(seed: OpportunitySeed): number {
  const start = new Date(seed.startDate);
  const end = new Date(seed.endDate);
  if (Number.isNaN(start.getTime()) || Number.isNaN(end.getTime())) {
    return 0;
  }
  const diff = Math.floor((end.getTime() - start.getTime()) / (1000 * 60 * 60 * 24));
  return Math.max(diff + 1, 1);
}

const buildFieldText = (seed: OpportunitySeed) =>
  [
    seed.title,
    seed.description,
    seed.farmName,
    seed.location.prefecture,
    seed.location.city,
    seed.location.address,
    seed.tags.join(" "),
  ]
    .join(" ")
    .toLowerCase();

const evaluateRules = (
  seed: OpportunitySeed,
  text: string,
  rules: KeywordRule[],
  allowedValues: Set<string>,
): Set<string> => {
  const result = new Set<string>();
  for (const rule of rules) {
    const matchedByPattern =
      rule.patterns?.some((pattern) => pattern.test(text)) ?? false;
    const matchedByPredicate = rule.predicate?.(seed, text) ?? false;
    if ((matchedByPattern || matchedByPredicate) && allowedValues.has(rule.value)) {
      result.add(rule.value);
    }
  }
  return result;
};

const buildOpportunity = (seed: OpportunitySeed): Opportunity => {
  const text = buildFieldText(seed);
  const interest = evaluateRules(seed, text, INTEREST_RULES, INTEREST_VALUES);
  const workstyle = evaluateRules(seed, text, WORKSTYLE_RULES, WORKSTYLE_VALUES);
  const farmTypes = evaluateRules(seed, text, FARM_TYPE_RULES, FARM_TYPE_VALUES);
  const managingFarmers = buildManagingFarmers(seed.id);
  const owner = buildOwner(managingFarmers);

  if (!interest.has("seasonal")) {
    interest.add("seasonal");
  }

  if (interest.has("livestock") && !farmTypes.has("livestock")) {
    farmTypes.add("livestock");
  }

  if (interest.has("orchard") && !farmTypes.has("orchard")) {
    farmTypes.add("orchard");
  }

  if (farmTypes.size === 0) {
    farmTypes.add("open_field");
  }

  if (workstyle.size === 0) {
    const duration = getDurationDays(seed);
    if (duration > 0 && duration <= 14) {
      workstyle.add("short_term");
    } else if (duration >= 30) {
      workstyle.add("migration");
    } else {
      workstyle.add("career_change");
    }
  }

  const adjustedLatLng = clampToToyohashiBoundary({
    lat: seed.location.lat,
    lng: seed.location.lng,
  });

  return {
    ...seed,
    location: {
      ...seed.location,
      lat: adjustedLatLng.lat,
      lng: adjustedLatLng.lng,
    },
    interestTags: Array.from(interest),
    workstyleTags: Array.from(workstyle),
    farmTypes: Array.from(farmTypes),
    managingFarmers,
    owner,
    chatRoomId: `chat-${seed.id}`,
  };
};

export const OPPORTUNITIES: Opportunity[] = OPPORTUNITY_SEEDS.map(buildOpportunity);

export const APPLICANTS: Applicant[] = [
  {
    id: "app-001",
    name: "山田 花子",
    message: "農業体験は初めてですが、地域貢献がしたくて応募しました。",
    status: "pending",
    appliedAt: "2025-04-02T09:00:00Z",
    opportunityId: "op-001",
    profile: {
      age: 21,
      occupation: "大学生",
      location: "愛知県 名古屋市",
    },
  },
  {
    id: "app-002",
    name: "高橋 蓮",
    message: "昨年も参加しました。収穫経験があります。",
    status: "approved",
    appliedAt: "2025-03-28T15:30:00Z",
    opportunityId: "op-024",
    profile: {
      age: 26,
      occupation: "フリーランス",
      location: "静岡県 浜松市",
    },
  },
  {
    id: "app-003",
    name: "李 美咲",
    message: "短期で参加できる仕事を探しています。",
    status: "pending",
    appliedAt: "2025-04-03T11:15:00Z",
    opportunityId: "op-033",
    profile: {
      age: 29,
      occupation: "会社員",
      location: "愛知県 岡崎市",
    },
  },
  {
    id: "app-004",
    name: "佐藤 光",
    message: "スマート農業に興味があり、現場で学びたいです。",
    status: "pending",
    appliedAt: "2025-04-15T14:45:00Z",
    opportunityId: "op-041",
    profile: {
      age: 24,
      occupation: "大学院生",
      location: "愛知県 豊橋市",
    },
  },
  {
    id: "app-005",
    name: "中村 美沙",
    message: "酪農の仕事に挑戦してみたいので応募しました。",
    status: "approved",
    appliedAt: "2025-04-22T08:20:00Z",
    opportunityId: "op-031",
    profile: {
      age: 31,
      occupation: "管理栄養士",
      location: "愛知県 豊川市",
    },
  },
  {
    id: "app-006",
    name: "ヴィクター 田中",
    message: "日本の農業イベント運営を経験したくてサインアップしました。",
    status: "pending",
    appliedAt: "2025-04-29T10:10:00Z",
    opportunityId: "op-050",
    profile: {
      age: 28,
      occupation: "イベントプランナー",
      location: "愛知県 一宮市",
    },
  },
];

